import Link from 'next/link'
import './globals.css'
import type { Metadata } from 'next'
import { Control } from './Control'

export const metadata: Metadata = {
  title: 'Web tutorials',
  description: 'Generated by HS',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const resp = await fetch('http://localhost:9000/topics', { cache: 'no-store' }); //{ next: { revalidate: 0 } }
  const topics = await resp.json();
  return (
    <html>
      <body>
        <h1><a href="/">WEB</a></h1>
        <ol>
          {topics.map((topic: any) => {
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  )
}
